language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1
  - jruby-9.2
before_install:
  - gem install rubygems-update -v '<3' && update_rubygems
  - gem update bundler
