language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.5
  - 2.4.2
  - ruby-head
  - jruby-9.1.6.0
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update bundler
