language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-9.1.6.0
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system
  - gem update bundler
