language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.5
  - 2.4.2
  - ruby-head
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
before_install:
  - gem update bundler
