language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.1.17.0
  - jruby-9.2.6.0
before_install:
  - gem install rubygems-update -v '<3' && update_rubygems
  - gem update bundler
